---
title: ""
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## WORK EXPERIENCE

### Memorial Sloan Kettering
**Data Analyst** | New York, NY | Dec. 2022 -- Present

- Optimized data processing pipeline using parallel computing and cluster technology, reducing computational time by 50%, leading to faster clinical insight
- Implemented advanced statistical techniques, including a robust method to quantify surgeons' contribution to outcome variation. This data-driven approach led to a redesigned feedback system, resulting in a 25% increase in patient survey completion rate and the establishment of a targeted surgeon shadowing program.
- Maintained and expanded the team's R package, implementing specialized functions to improve coding efficiency and optimized validation workflows. Resulting in a 70% reduction in validation time and significantly enhancing the reliability and reproducibility of downstream analyses
- Developed and executed complex SQL queries to create robust patient cohorts, joining and preprocessing data from multiple clinical databases.

### Weill Cornell Medicine
**Computational Research Technician** | New York, NY | June 2021 -- Dec. 2022

- Engineered a scalable bioinformatics pipeline for high-throughput assembly of genomes, deploying it on a Linux-based HPC cluster using SLURM schedulers for parallel processing.
- Conducted genome-wide association studies on WGS data to identify genomic variations in fungal strains related to Inflammatory Bowel Disease using advanced bioinformatics tools.
- Leveraged data visualization libraries (e.g., ggplot2, ploty) and web framework (Shiny) in R to construct interactive dashboards showcasing differential analysis between IDB cohorts.
- Developed an in-house database using MySQL to efficiently manage and query bioinformatics data.

### Massachusetts General Hospital
**Undergraduate Researcher** | Charlestown, MA | Sept. 2018 -- May 2019

- Developed a machine learning model using Support Vector Machines and Principal Component Analysis in R to predict Alzheimer's risk, achieving 90%+ accuracy.
- Architected a scalable ETL pipeline in R, integrating API data retrieval and advanced data wrangling techniques to process large-scale hematological datasets.
- Optimized SVM hyperparameters through grid search and cross-validation, ensuring model generalizability and mitigating overfitting.

## EDUCATION

### Columbia University
**Master of Science in Biostatistics** | New York, NY | May 2022

GPA: 4.0/4.0

### Boston University
**Bachelor of Science in Biomedical Engineering** | Boston, MA | May 2019

GPA: 3.4/4.0 *Cum Laude*

## PROJECTS

- [Simulation Project](./projects/simulation_project.html) - Columbia University, Spring 2022
  - Developed a complex simulation study to evaluate statistical power in clinical trials
- [March Madness 2021 Machine Learning](./projects/march_madness_2021.html) - Personal Project, March 2021
  - Conducted predictive analysis of NCAA basketball tournament outcomes using historical data
- [Comparing Pandemics](https://jak2312.shinyapps.io/shiny_dashboard/) - Columbia University, Fall 2021
  - Created a dynamic dashboard for visualizing and choropleth map for comparing different pandemics
- [Instacart Shiny Dashboard](dashboard.html) - Columbia University, Fall 2021
  - Designed an interactive tool for exploring Instacart customer behavior and product trends
- [Linear Modeling of Hate Crimes](./projects/hate_crime.pdf) - Columbia University, Spring 2021
  - Applied advanced statistical methods to analyze factors influencing hate crime incidence rates

## SKILLS & INTERESTS

- **Technical Skills:** R Programming; SQL; Python; Statistical Programming; Advanced Statistics; High-Performance Computing; ETL; Agile Methodologies; Research Collaboration; Git
- **Interests/Hobbies:** 3D Printing & Design; Mechanical Keyboards; Pickleball; World of Warcraft; Overwatch
